module.exports = {

    USER_REGISTERED: "USER_REGISTERED",
    USER_LOGIN: "USER_LOGIN",

    ADMIN_REGISTERED: "ADMIN_REGISTERED",
    ADMIN_LOGIN: "ADMIN_LOGIN",

    MOVIE_CREATED: "MOVIE_CREATED",
    MOVIE_UPDATED: "MOVIE_UPDATED",
    MOVIE_DELETED: "MOVIE_DELETED",

    BOOKING_CREATED: "BOOKING_CREATED",
    BOOKING_CANCELLED: "BOOKING_CANCELLED",

    WALLET_TOPUP: "WALLET_TOPUP",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_REFUND: "PAYMENT_REFUND",

};